name: secureme_id
description: Blockchain Identity Locker for secure storage of personal documents and KYC verification
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  lottie: ^2.6.0
  flutter_slidable: ^3.0.0

  # State Management
  provider: ^6.0.5
  flutter_bloc: ^8.1.3

  # Biometrics
  local_auth: ^2.1.6

  # Storage and Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  path_provider: ^2.0.15

  # ICP & Blockchain
  flutter_js: ^0.8.2  
  js: ^0.6.7      
  hex: ^0.2.0
  ed25519_hd_key: ^2.2.0

  # Cryptography
  encrypt: ^5.0.1
  crypto: ^3.0.3
  pointycastle: ^3.7.3

  # Networking
  dio: ^5.3.2
  http: ^1.3.0 

  # Utils
  uuid: ^3.0.7
  intl: ^0.18.1
  image_picker: ^1.0.2
  permission_handler: ^10.4.3
  camera: ^0.10.5+2
  file_picker: ^5.3.3
  bip39: ^1.0.6
  web3dart: ^2.6.1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/js/        # For agent-js scripts

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true 